# Generated by Django 3.2 on 2021-12-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='ビールの銘柄')),
                ('degree', models.FloatField(verbose_name='アルコール度数')),
                ('color', models.CharField(max_length=10, verbose_name='ビールの色')),
                ('srm', models.FloatField(verbose_name='米国醸造化学者学会によるビールの色の数値指標')),
                ('bitterness', models.FloatField(verbose_name='ビールの苦味IBU')),
            ],
        ),
        migrations.CreateModel(
            name='BeerStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=20, verbose_name='ビアスタイルの名称')),
                ('birthplace', models.CharField(max_length=20, verbose_name='ビアスタイルの発祥地')),
                ('fermentation', models.CharField(max_length=10, verbose_name='醸造方法')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='会員の名前')),
                ('user_name', models.CharField(max_length=20, verbose_name='会員のユーザー名')),
                ('sex', models.CharField(choices=[('M', '男性'), ['F', '女性']], max_length=1, verbose_name='会員の性別')),
                ('password', models.CharField(max_length=15, verbose_name='会員のパスワード')),
                ('address', models.CharField(max_length=30, verbose_name='会員の出身地')),
                ('birth_date', models.DateField(verbose_name='会員の生年月日')),
                ('mail', models.EmailField(max_length=254, verbose_name='会員のeメールアドレス')),
            ],
        ),
        migrations.CreateModel(
            name='BeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='ビール銘柄に関するレビュー文')),
                ('rate', models.IntegerField(choices=[(1, '好き'), (-1, 'イマイチ')], verbose_name='会員の好み')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.beerbrand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
            ],
        ),
        migrations.AddField(
            model_name='beerbrand',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.beerstyle'),
        ),
    ]
