# Generated by Django 3.2 on 2022-01-05 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='ビールの銘柄')),
                ('degree', models.FloatField(verbose_name='アルコール度数')),
                ('color', models.CharField(max_length=10, verbose_name='ビールの色')),
                ('bitterness', models.FloatField(verbose_name='ビールの苦味IBU')),
            ],
        ),
        migrations.CreateModel(
            name='BeerStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=20, verbose_name='ビアスタイルの名称')),
                ('birthplace', models.CharField(max_length=20, verbose_name='ビアスタイルの発祥地')),
                ('fermentation', models.CharField(max_length=10, verbose_name='醸造方法')),
                ('description', models.TextField(verbose_name='ビアスタイルの説明')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', '男性'), ['F', '女性']], max_length=1, verbose_name='会員の性別')),
                ('post_code', models.CharField(max_length=10, verbose_name='会員の郵便番号')),
                ('address', models.CharField(max_length=30, verbose_name='会員の住所')),
                ('birth_date', models.DateField(verbose_name='会員の生年月日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='ビール銘柄に関するレビュー文')),
                ('preference', models.IntegerField(choices=[(1, '好き'), (-1, '嫌い')], verbose_name='会員の好み')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.beerbrand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
            ],
        ),
        migrations.AddField(
            model_name='beerbrand',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.beerstyle'),
        ),
    ]
