# Generated by Django 3.2 on 2021-12-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerstyle',
            name='desciption',
            field=models.TextField(default='description about style'),
            preserve_default=False,
        ),
    ]
