# Generated by Django 3.2 on 2022-01-12 07:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='ビール銘柄')),
                ('degree', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='アルコール度数')),
                ('color', models.CharField(max_length=10, verbose_name='ビールの色')),
                ('bitterness', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='IBU')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.beerstyle')),
            ],
        ),
    ]
